version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  code:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      APP_MONGODB_URL: mongodb://mongo:27017
      ANTHROPIC_API_KEY: ${CLAUDE_API_KEY}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      GROQ_API_KEY: ${GROQ_API_KEY}
    depends_on:
      - mongo
    volumes:
      - .:/api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      N8N_HOST: localhost
      N8N_PORT: 5678
      N8N_PROTOCOL: http
      WEBHOOK_URL: http://localhost:5678
      N8N_API_KEY: ${N8N_API_KEY}
      N8N_WORKFLOW_CALLER_POLICY_DEFAULT_OPTION: any
      N8N_DISABLE_WORKFLOW_LOCKING: "true"
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      - code

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok
    restart: unless-stopped
    command: http code:8000
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    ports:
      - "4040:4040"
    depends_on:
      - code

volumes:
  mongo_data:
  n8n_data: