version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  code:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      APP_MONGODB_URL: mongodb://mongo:27017
      ANTHROPIC_API_KEY: ${CLAUDE_API_KEY}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
    depends_on:
      - mongo
    volumes:
      - .:/api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok
    restart: unless-stopped
    command: http code:8000
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    ports:
      - "4040:4040"
    depends_on:
      - code

volumes:
  mongo_data: